name = "JETLS"
uuid = "a3b70258-0602-4ee2-b5a6-54c2470400db"
version = "0.0.0"
authors = ["Shuhei Kadowaki <aviatesk@gmail.com>"]

[workspace]
projects = ["test"]

[deps]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuliaLowering = "f3c80556-a63f-4383-b822-37d64f81a311"
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[sources]
# JET = {url = "https://github.com/aviatesk/JET.jl#master"}
# JuliaLowering = {url = "https://github.com/mlechu/JuliaLowering.jl#fix-nightly"}

[compat]
JET = "0.10.5"
JSON3 = "1.14.1"
JuliaLowering = "1.0.0"
JuliaSyntax = "1.0"
Pkg = "1.11.0"
REPL = "1.11.0"
StructTypes = "1.11.0"
URIs = "1.5"
julia = "1.12"
