name = "JETLS"
uuid = "a3b70258-0602-4ee2-b5a6-54c2470400db"
version = "0.0.0"
authors = ["Shuhei Kadowaki <aviatesk@gmail.com>"]

[workspace]
projects = ["docs", "test", "scripts"]

[deps]
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JuliaLowering = "f3c80556-a63f-4383-b822-37d64f81a311"
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
LSP = "880dcf91-6fde-4251-87fc-bfd84012291a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[sources]
JET = {rev = "8fe5f1b", url = "https://github.com/aviatesk/JET.jl"}
JuliaLowering = {rev = "avi/JETLS-JSJL-head-2026-01-09", subdir = "JuliaLowering", url = "https://github.com/JuliaLang/julia"}
JuliaSyntax = {rev = "avi/JETLS-JSJL-head-2026-01-09", subdir = "JuliaSyntax", url = "https://github.com/JuliaLang/julia"}
LSP = {path = "LSP"}

[compat]
Configurations = "0.17.6"
Glob = "1.4"
JET = "0.10.6"
JuliaLowering = "1"
JuliaSyntax = "2"
LSP = "0.1"
Markdown = "1.11.0"
Pkg = "1.11.0"
PrecompileTools = "1.3.2"
Preferences = "1.4.3"
Profile = "1.11.0"
REPL = "1.11.0"
Revise = "3.13"
Sockets = "1.11.0"
TOML = "1.0.3"
julia = "1.12"

[apps.jetls]
julia_flags = ["--startup-file=no", "--history-file=no", "--threads=auto"]
