name = "JETLS"
uuid = "a3b70258-0602-4ee2-b5a6-54c2470400db"
version = "0.0.0"
authors = ["Shuhei Kadowaki <aviatesk@gmail.com>"]

[workspace]
projects = ["docs", "test", "scripts"]

[deps]
CodeTracking = "29b28462-3302-58bb-873a-3f58224955cc"
Compiler = "8499cccf-07fb-5365-ac3a-39ae87615c05"
Configurations = "0e024541-5ab8-52a1-ab45-c6c348770b4a"
ExproniconLite = "c4ea0d7b-0a8a-57b2-be88-2cd5ead728ce"
Glob = "a6ef924f-2b2c-5d99-b812-8edbc1441234"
JET = "d18a8d2a-b6cf-5b35-ae77-db04d04d451d"
JSON3 = "00ac8d46-747e-5902-8e12-fdfc767369c7"
JuliaInterpreter = "87c368a4-672f-5de1-91ff-3cc7fc652fab"
JuliaLowering = "7ba39d99-9390-5ff4-b3a7-c9cea37c1861"
JuliaSyntax = "02a177f8-2b16-5240-a0b4-02ed40703cda"
LSP = "ba3d5f2d-0240-5843-8ab5-e1c74856c201"
LoweredCodeUtils = "01ede001-ea10-5720-9c31-2e53839707a9"
MacroTools = "73a1cfca-4736-53e3-b924-35a7291c571e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OrderedCollections = "64c61135-0f01-5c34-beb9-07fc02084e85"
Parsers = "2bf889ff-109e-5fa9-9ba3-339ee07cbe67"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "32931bc0-5014-5544-84d5-53636ff9f6c5"
Preferences = "cc588e5a-7be0-5224-8a6a-549b21958db9"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Revise = "d54aa4ff-5f0d-5e64-8d83-7613e0a93f9b"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
StructTypes = "66bcceda-d870-5865-93dd-65803322e79e"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[sources]
CodeTracking = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/CodeTracking", url = "https://github.com/aviatesk/JETLS.jl"}
Compiler = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/Compiler", url = "https://github.com/aviatesk/JETLS.jl"}
Configurations = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/Configurations", url = "https://github.com/aviatesk/JETLS.jl"}
ExproniconLite = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/ExproniconLite", url = "https://github.com/aviatesk/JETLS.jl"}
Glob = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/Glob", url = "https://github.com/aviatesk/JETLS.jl"}
JET = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/JET", url = "https://github.com/aviatesk/JETLS.jl"}
JSON3 = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/JSON3", url = "https://github.com/aviatesk/JETLS.jl"}
JuliaInterpreter = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/JuliaInterpreter", url = "https://github.com/aviatesk/JETLS.jl"}
JuliaLowering = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/JuliaLowering", url = "https://github.com/aviatesk/JETLS.jl"}
JuliaSyntax = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/JuliaSyntax", url = "https://github.com/aviatesk/JETLS.jl"}
LSP = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/LSP", url = "https://github.com/aviatesk/JETLS.jl"}
LoweredCodeUtils = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/LoweredCodeUtils", url = "https://github.com/aviatesk/JETLS.jl"}
MacroTools = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/MacroTools", url = "https://github.com/aviatesk/JETLS.jl"}
OrderedCollections = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/OrderedCollections", url = "https://github.com/aviatesk/JETLS.jl"}
Parsers = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/Parsers", url = "https://github.com/aviatesk/JETLS.jl"}
PrecompileTools = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/PrecompileTools", url = "https://github.com/aviatesk/JETLS.jl"}
Preferences = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/Preferences", url = "https://github.com/aviatesk/JETLS.jl"}
Revise = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/Revise", url = "https://github.com/aviatesk/JETLS.jl"}
StructTypes = {rev = "95826370cca26dfec9652607d10972a08f74901d", subdir = "vendor/StructTypes", url = "https://github.com/aviatesk/JETLS.jl"}

[compat]
Configurations = "0.17.6"
Glob = "1.4"
JET = "0.10.6"
JuliaLowering = "1"
JuliaSyntax = "2"
LSP = "0.1"
Markdown = "1.11.0"
Pkg = "1.11.0"
PrecompileTools = "1.3.2"
Preferences = "1.4.3"
Profile = "1.11.0"
REPL = "1.11.0"
Revise = "3.13"
Sockets = "1.11.0"
TOML = "1.0.3"
julia = "1.12"

[apps.jetls]
julia_flags = ["--startup-file=no", "--history-file=no", "--threads=auto"]
