name = "LSP"
uuid = "880dcf91-6fde-4251-87fc-bfd84012291a"
version = "0.1.0"
authors = ["Shuhei Kadowaki <aviatesk@gmail.com>"]

[workspace]
projects = ["test"]

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
StructUtils = "ec057cc2-7a8d-4b58-b3b3-92acb9f63b42"

[compat]
JSON = "1.3"
StructUtils = "2.6.0"
