name = "LSP"
uuid = "880dcf91-6fde-4251-87fc-bfd84012291a"
version = "0.1.0"
authors = ["Shuhei Kadowaki <aviatesk@gmail.com>"]

[workspace]
projects = ["test"]

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
JSON3 = "1.14.3"
PrecompileTools = "1.3.3"
StructTypes = "1.11.0"
