name = "JSONRPC"
uuid = "a2756949-8476-49a1-a294-231eace0f283"
version = "0.1.0"
authors = ["Shuhei Kadowaki <aviatesk@gmail.com>"]

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
JSON = "1.3"
