name: LSP.jl

on:
  push:
    branches:
      - master
    paths:
      - "LSP/**"
      - ".github/workflows/LSP.jl.yml"
  pull_request:
    branches-ignore:
      - release
    paths:
      - "LSP/**"
      - ".github/workflows/LSP.jl.yml"

jobs:
  LSP:
    name: Test LSP.jl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.12" # most stable version
          arch: x64
      - uses: julia-actions/cache@v2
      - name: test LSP
        shell: julia --color=yes --project=. {0}    # this is necessary for the next command to work on Windows
        run: 'using Pkg; Pkg.activate(normpath(pwd(), "LSP")); Pkg.instantiate(); Pkg.test(; coverage=true)'
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: LSP/src
      - uses: codecov/codecov-action@v5
        with:
          flags: LSP.jl
